version: '3'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    hostname: emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "18083:18083"
    networks:
      - mynet

  nodered:
    image: nodered/node-red:latest
    hostname: nodered
    container_name: nodered
    ports:
      - "1880:1880"
    networks:
      - mynet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9500:9500"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - emqx
      - nodered
    networks:
      - mynet

networks:
  mynet:
    driver: bridge