version: '3'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    hostname: emqx
    restart: always
    ports:
      - "9500:1883"
    networks:
      - mynet
    volumes:
      - ./emqx/vol-emqx-data:/opt/emqx/data
      - ./emqx/vol-emqx-log:/opt/emqx/log

  nodered:
    image: nodered/node-red:latest
    hostname: nodered
    container_name: nodered
    volumes:
      - ./nodered_data:/data
    networks:
      - mynet

  db:
    image: mysql:5.7
    container_name: dbsql
    hostname: mysql_ht
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data/sql:/var/lib/mysql
    networks:
      - mynet

  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    ports:
      - "8090:80"
    restart : always
    environment:
      PMA_HOST : db
      MYSQL_ROOT_PASSWORD : example
    networks:
      - mynet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9500:9500"
    volumes:
      - ./nginx_data/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - emqx
      - nodered
      - phpmyadmin
    networks:
      - mynet


networks:
  mynet:
    driver: bridge